[region1]
id="region1"
size = 3
neighbors = ["region2","region4"]
rivers=["region2"]


[region2]
id="region2"
size = 3
terrain = "mountain"
neighbors = ["region1","region3"]
rivers = ["region1"]


[region3]
id="region3"
size = 3
neighbors = ["region2","region6"]

[region4]
id="region4"
size = 3
terrain = "plain"
neighbors = ["region1","region5"]


[region5]
id="region5"
size = 3
neighbors = ["region4"]

[region6]
id="region6"
size = 3
neighbors = ["region3"]
